### ISSUE TITLE
Should Not Start Work on Cases Closed within Timeout

### ISSUE THREAD

**Issue by ambroselittle** [CentralReach/FogMachine#8]
1. Click to open a case.
2. Click the x to close it before the delay.

Actual:
After configured delay, it pops up the notification it will start then starts (if you don't cancel). 

Expected:
If you close a case before the configured delay, it should cancel/not start work on it.

**Comment by boydc7** [comment]
Wow, how did I miss that one

**Comment by ambroselittle** [comment]
What's that old saying about how code never survives the first encounter with real users? 👯
